endpoint:
  ibc:
    channels-beta: '/ibc/core/channel/v1beta1/channels'
    channels: '/ibc/core/channel/v1/channels'
    channels-by-num: '/ibc/core/channel/v1/channels/%s/ports/transfer'
    channels-by-num-beta: '/ibc/core/channel/v1beta1/channels/%s/ports/transfer'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        jdbc:
          lob:
            non_contextual_creation: true